### ISSUE TITLE
Applications using playwright-elixir must independently install playwright js

### ISSUE THREAD

**Issue by sax** [geometerio/playwright-elixir#20]
This adds an extra integration step to every application that tries to use this library.

Ideas:
* Add documentation about this dependency and how to resolve it.
* playwright-elixir can ship playwright in its priv directory.
* This library can check for playwright being installed in the environment, and tell you how to install it.

**Comment by sax** [comment]
One thing to watch out for is a match between this library's known compatibility with the installed version of playwright. If there is a mismatch, this library at the very least should print a warning.

**Comment by coreyti** [comment]
I believe this is handled in the "[Bundle/config Playwright node CLI](https://github.com/geometerio/playwright-elixir/commit/84536469bc312d5cef3d8c8975f8d0689ad7793b)" commit.

@sax, thoughts?

**Comment by coreyti** [comment]
Closing, as I believe this is resolve.
