### ISSUE TITLE
Remove `playwright_cli_path` `ConnectOptions`

### ISSUE THREAD

**Issue by coreyti** [geometerio/playwright-elixir#25]
I believe that this is intended to be the `executable_path` from `LaunchOptions`.

@dbrody, thoughts on this?

cc @woodward

**Comment by dbrody** [comment]
Those are two different things, please do NOT remove `playwright_cli_path`.

1. `executable_path` is the path to the Chrome executable
2. `playwright_cli_path` is the path the playwright `cli.js` file within the npm package used to communicate with chrome

Exposing both of those options is important as this library is used in different environments and installation methods.

**Comment by coreyti** [comment]
Ah yes, I was conflating those paths.

I do think that it makes sense to move `playwright_cli_path` to `LaunchOptions` instead of being on `ConnectOptions`. The `ConnectionOptions` configuration is meant to be applicable for cases when connecting to a running Playwright over WebSockets. No CLI is involved in those cases.

It would also make sense to have `playwright_cli_path` in `LaunchServerOptions`, once we get to implementing that functionality.

**Comment by coreyti** [comment]
An alternative might be to include some other collection of options, for configuration that is unique to playwright-elixir, such as this. The `ConnectOptions` and `LaunchOptions` were intended to match the [equivalent](https://github.com/microsoft/playwright/blob/0936ce2bbd23dc998ad44fd83ad1134cf298f6b9/packages/playwright-core/src/client/types.ts#L71) [types](https://github.com/microsoft/playwright/blob/0936ce2bbd23dc998ad44fd83ad1134cf298f6b9/packages/playwright-core/src/client/types.ts#L67) in Node.js Playwright.

**Comment by dbrody** [comment]
@coreyti Got it! Whatever you think is best, as long as the option to configure it is still available.

**Comment by coreyti** [comment]
The "[Bundle/config Playwright node CLI](https://github.com/geometerio/playwright-elixir/commit/84536469bc312d5cef3d8c8975f8d0689ad7793b)" commit includes the change to move `:playwright_cli_path` from `ConnectOptions` to `LaunchOptions`.
