### ISSUE TITLE
Allow for Page listeners

### ISSUE THREAD

**Issue by dbrody** [geometerio/playwright-elixir#8]
Is there a way to retrieve listener events for page requests? I see the `Page.on/3` and I see it can receive `console` type events, but what about [Request](https://playwright.dev/docs/api/class-request/) events as per Playwright?

How can I listen to requests?

**Comment by dbrody** [comment]
So, it looks like `Playwright.Runner.Channel.Event` already taps into those events but they are just not captured meaningfuly.

If I uncomment this line:
https://github.com/geometerio/playwright-elixir/blob/4eeea1c126090173d5316331d86bec9995edecdf/lib/playwright/runner/channel/event.ex#L72

Then my trace shows a bunch of:
```
[warn] Event.handle/3 for unhandled method: "loadstate"; event data: %{guid: "frame@bfc9405a8e139b3df64aee37159f45ab", method: "loadstate", params: %{add: "load"}}
[warn] Event.handle/3 for unhandled method: "load"; event data: %{guid: "page@8f2f89be9661e4d97b71cd5dc7837d49", method: "load"}
[warn] Event.handle/3 for unhandled method: "request"; event data: %{guid: "browser-context@924641addcf7f5aedd83672e2ea60b66", method: "request", params: %{page: %{guid: "page@8f2f89be9661e4d97b71cd5dc7837d49"}, request: %{guid: "request@12408684b12e7a7565fa51fde244548f"}}}
[warn] Event.handle/3 for unhandled method: "response"; event data: %{guid: "browser-context@924641addcf7f5aedd83672e2ea60b66", method: "response", params: %{page: %{guid: "page@8f2f89be9661e4d97b71cd5dc7837d49"}, response: %{guid: "response@300ae04e99a62c2cefff62aae4933133"}}}
[warn] Event.handle/3 for unhandled method: "response"; event data: %{guid: "browser-context@924641addcf7f5aedd83672e2ea60b66", method: "response", params: %{page: %{guid: "page@8f2f89be9661e4d97b71cd5dc7837d49"}, response: %{guid: "response@c4b8a99a98cbcc6751b35a324d71403d"}}}
```

Any advice on how to tap into and handle these events? Is this duplicate work from elsewhere or would this be a helpful addition? If so, how would you advise proceeding?

**Comment by dbrody** [comment]
So I'm able to access the `Playwright.Response` of each request response on the `response` event. However the response doesn't include the body. How do we access the body of the responses?

**Comment by dbrody** [comment]
Sorry for the clutter here but I'm not sure where else to post this....I'm getting closer but still stuck...

So I now have a callback which gets the `Playwright.Response` objects. The goal is to get the body content of the response.

I see the `ResponseBodyParams` in the playwright cli code which mirrors other calls. That seems to match the `Responase.body()` method.

However, when I try to do something like `response |> Channel.send("body")` it fails because of the timeout from `GenServer.call` waiting for the response it seems. Other methods I've tried like `PageContext |> Channel.send("cookies")` seems to work.

Is there something I'm missing for async calls or something? Why does playwright-elixir not get the response body?

**Comment by coreyti** [comment]
Hi @dbrody,

Thanks for opening this up, and sharing your thoughts and findings! As you noticed, there's quite a lot that is not yet implemented to bring playwright-elixir to parity with with the other implementations. Specific needs, such as this, are generally driving the work done, and I believe that I already have some work underway that is related. Will take a look at implementing today.

**Comment by dbrody** [comment]
@coreyti Awesome!

**Comment by dbrody** [comment]
@coreyti Any update on this?

**Comment by coreyti** [comment]
Hi @dbrody,

Thanks for checking in!

Indeed... in turns out that implementing this correctly is driving out a bunch more incomplete work. This is great, because it means more of the API will be complete. It also means it's taking a bit of time. I hope to have something pushed by this evening (PST).

**Comment by coreyti** [comment]
Update: we pushed some changes today that are headed toward this implementation. Most of the changes so far are indirectly related, but are setting the stage for the needs here.

**Comment by dbrody** [comment]
Great. I'll take a look soon.

This is a blocking item for me so any suggestions or directions as to how to get response body from response objects would be helpful. I would be happy to assist and generate some pull requests.

**Comment by dbrody** [comment]
Thank you also! Those changes do look like a great step towards getting this implemented.

One thing I noticed on my end was the SEND body command on the response would hang waiting for a response from playwright.

Looking forward to getting these features!

**Comment by coreyti** [comment]
Hi @dbrody,

We've just pushed [some changes](https://github.com/geometerio/playwright-elixir/commit/c1fe4b9c947ab3448f73265179d6cb55419c72b4) that I believe get you the start of what you're looking for, allowing something like:

```elixir
# response from `.goto`:
response = Page.goto(page, url)
assert Response.body(response) == "<p>content</p>"

# response in a network event handler:
Page.on(page, "response", fn _, %{params: %{response: response}} ->
  assert Response.body(response) == "<p>content</p>"
end)
```

Note that the initial `Response.body/1` implementation is very simple and likely would not handle things like web pages with particularly large bodies.

I believe that the changes so far should handle the hanging send that you noted. Take a look and let us know how it goes.

**Comment by coreyti** [comment]
And, pull requests are welcome. :)

**Comment by dbrody** [comment]
Awesome, I will check it out. Thank you!

Also, who is "us"? I dont see much about geometerio...

Anyway, thank you!

**Comment by coreyti** [comment]
> who is "us"?

Good question :) 

Geometer (https://geometer.io/) is a startup incubator. A bunch of us like Elixir. I'm actually new to Elixir, and learning a **ton** by helping to build this Playwright port.

**Comment by dbrody** [comment]
Awesome! I'll reach out directly to not pollute this issue even more. Thanks again!

**Comment by dbrody** [comment]
The new API is a great improvement. I'll follow up on a new issue with more details snags now. Thanks!
